/*
 * Open Payments Authorization Server
 * The Open Payments API is secured via [GNAP](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol). This specification describes the Open Payments Authorization Server API, which is an opinionated GNAP Server API.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: tech@interledger.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fliqa.interledger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.fliqa.interledger.client.model.LimitsOutgoing;
import java.net.URI;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.fliqa.interledger.ApiClient;
/**
 * AccessOutgoing
 */
@JsonPropertyOrder({
  AccessOutgoing.JSON_PROPERTY_TYPE,
  AccessOutgoing.JSON_PROPERTY_ACTIONS,
  AccessOutgoing.JSON_PROPERTY_IDENTIFIER,
  AccessOutgoing.JSON_PROPERTY_LIMITS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class AccessOutgoing {
  /**
   * The type of resource request as a string.  This field defines which other fields are allowed in the request object.
   */
  public enum TypeEnum {
    OUTGOING_PAYMENT(String.valueOf("outgoing-payment"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private TypeEnum type;

  /**
   * Gets or Sets actions
   */
  public enum ActionsEnum {
    CREATE(String.valueOf("create")),
    
    READ(String.valueOf("read")),
    
    READ_ALL(String.valueOf("read-all")),
    
    LIST(String.valueOf("list")),
    
    LIST_ALL(String.valueOf("list-all"));

    private String value;

    ActionsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionsEnum fromValue(String value) {
      for (ActionsEnum b : ActionsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTIONS = "actions";
  @javax.annotation.Nonnull
  private Set<ActionsEnum> actions = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @javax.annotation.Nonnull
  private URI identifier;

  public static final String JSON_PROPERTY_LIMITS = "limits";
  private JsonNullable<LimitsOutgoing> limits = JsonNullable.<LimitsOutgoing>undefined();

  public AccessOutgoing() { 
  }

  public AccessOutgoing type(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The type of resource request as a string.  This field defines which other fields are allowed in the request object.
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public AccessOutgoing actions(@javax.annotation.Nonnull Set<ActionsEnum> actions) {
    this.actions = actions;
    return this;
  }

  public AccessOutgoing addActionsItem(ActionsEnum actionsItem) {
    if (this.actions == null) {
      this.actions = new LinkedHashSet<>();
    }
    this.actions.add(actionsItem);
    return this;
  }

  /**
   * The types of actions the client instance will take at the RS as an array of strings.
   * @return actions
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Set<ActionsEnum> getActions() {
    return actions;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_ACTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActions(@javax.annotation.Nonnull Set<ActionsEnum> actions) {
    this.actions = actions;
  }


  public AccessOutgoing identifier(@javax.annotation.Nonnull URI identifier) {
    this.identifier = identifier;
    return this;
  }

  /**
   * A string identifier indicating a specific resource at the RS.
   * @return identifier
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getIdentifier() {
    return identifier;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentifier(@javax.annotation.Nonnull URI identifier) {
    this.identifier = identifier;
  }


  public AccessOutgoing limits(@javax.annotation.Nullable LimitsOutgoing limits) {
    this.limits = JsonNullable.<LimitsOutgoing>of(limits);
    return this;
  }

  /**
   * Get limits
   * @return limits
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public LimitsOutgoing getLimits() {
        return limits.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LIMITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<LimitsOutgoing> getLimits_JsonNullable() {
    return limits;
  }
  
  @JsonProperty(JSON_PROPERTY_LIMITS)
  public void setLimits_JsonNullable(JsonNullable<LimitsOutgoing> limits) {
    this.limits = limits;
  }

  public void setLimits(@javax.annotation.Nullable LimitsOutgoing limits) {
    this.limits = JsonNullable.<LimitsOutgoing>of(limits);
  }


  /**
   * Return true if this access-outgoing object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessOutgoing accessOutgoing = (AccessOutgoing) o;
    return Objects.equals(this.type, accessOutgoing.type) &&
        Objects.equals(this.actions, accessOutgoing.actions) &&
        Objects.equals(this.identifier, accessOutgoing.identifier) &&
        equalsNullable(this.limits, accessOutgoing.limits);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, actions, identifier, hashCodeNullable(limits));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessOutgoing {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `actions` to the URL query string
    if (getActions() != null) {
      int i = 0;
      for (String _item : getActions().stream().map(it -> it.value).toList()) {
        joiner.add(String.format("%sactions%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(ApiClient.valueToString(_item), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
      i++;
    }

    // add `identifier` to the URL query string
    if (getIdentifier() != null) {
      joiner.add(String.format("%sidentifier%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getIdentifier()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `limits` to the URL query string
    if (getLimits() != null) {
      joiner.add(getLimits().toUrlQueryString(prefix + "limits" + suffix));
    }

    return joiner.toString();
  }
}

