/*
 * Open Payments Authorization Server
 * The Open Payments API is secured via [GNAP](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol). This specification describes the Open Payments Authorization Server API, which is an opinionated GNAP Server API.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: tech@interledger.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fliqa.interledger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.fliqa.interledger.client.model.AccessIncoming;
import io.fliqa.interledger.client.model.AccessOutgoing;
import io.fliqa.interledger.client.model.AccessQuote;
import io.fliqa.interledger.client.model.LimitsOutgoing;
import java.net.URI;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.fliqa.interledger.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
@JsonDeserialize(using = AccessItem.AccessItemDeserializer.class)
@JsonSerialize(using = AccessItem.AccessItemSerializer.class)
public class AccessItem extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(AccessItem.class.getName());

    public static class AccessItemSerializer extends StdSerializer<AccessItem> {
        public AccessItemSerializer(Class<AccessItem> t) {
            super(t);
        }

        public AccessItemSerializer() {
            this(null);
        }

        @Override
        public void serialize(AccessItem value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class AccessItemDeserializer extends StdDeserializer<AccessItem> {
        public AccessItemDeserializer() {
            this(AccessItem.class);
        }

        public AccessItemDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public AccessItem deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize AccessIncoming
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (AccessIncoming.class.equals(Integer.class) || AccessIncoming.class.equals(Long.class) || AccessIncoming.class.equals(Float.class) || AccessIncoming.class.equals(Double.class) || AccessIncoming.class.equals(Boolean.class) || AccessIncoming.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((AccessIncoming.class.equals(Integer.class) || AccessIncoming.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((AccessIncoming.class.equals(Float.class) || AccessIncoming.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (AccessIncoming.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (AccessIncoming.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(AccessIncoming.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'AccessIncoming'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'AccessIncoming'", e);
            }

            // deserialize AccessOutgoing
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (AccessOutgoing.class.equals(Integer.class) || AccessOutgoing.class.equals(Long.class) || AccessOutgoing.class.equals(Float.class) || AccessOutgoing.class.equals(Double.class) || AccessOutgoing.class.equals(Boolean.class) || AccessOutgoing.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((AccessOutgoing.class.equals(Integer.class) || AccessOutgoing.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((AccessOutgoing.class.equals(Float.class) || AccessOutgoing.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (AccessOutgoing.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (AccessOutgoing.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(AccessOutgoing.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'AccessOutgoing'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'AccessOutgoing'", e);
            }

            // deserialize AccessQuote
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (AccessQuote.class.equals(Integer.class) || AccessQuote.class.equals(Long.class) || AccessQuote.class.equals(Float.class) || AccessQuote.class.equals(Double.class) || AccessQuote.class.equals(Boolean.class) || AccessQuote.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((AccessQuote.class.equals(Integer.class) || AccessQuote.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((AccessQuote.class.equals(Float.class) || AccessQuote.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (AccessQuote.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (AccessQuote.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(AccessQuote.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'AccessQuote'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'AccessQuote'", e);
            }

            if (match == 1) {
                AccessItem ret = new AccessItem();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for AccessItem: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public AccessItem getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "AccessItem cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public AccessItem() {
        super("oneOf", Boolean.FALSE);
    }

    public AccessItem(AccessIncoming o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public AccessItem(AccessOutgoing o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public AccessItem(AccessQuote o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("AccessIncoming", AccessIncoming.class);
        schemas.put("AccessOutgoing", AccessOutgoing.class);
        schemas.put("AccessQuote", AccessQuote.class);
        JSON.registerDescendants(AccessItem.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return AccessItem.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * AccessIncoming, AccessOutgoing, AccessQuote
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(AccessIncoming.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(AccessOutgoing.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(AccessQuote.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be AccessIncoming, AccessOutgoing, AccessQuote");
    }

    /**
     * Get the actual instance, which can be the following:
     * AccessIncoming, AccessOutgoing, AccessQuote
     *
     * @return The actual instance (AccessIncoming, AccessOutgoing, AccessQuote)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `AccessIncoming`. If the actual instance is not `AccessIncoming`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AccessIncoming`
     * @throws ClassCastException if the instance is not `AccessIncoming`
     */
    public AccessIncoming getAccessIncoming() throws ClassCastException {
        return (AccessIncoming)super.getActualInstance();
    }

    /**
     * Get the actual instance of `AccessOutgoing`. If the actual instance is not `AccessOutgoing`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AccessOutgoing`
     * @throws ClassCastException if the instance is not `AccessOutgoing`
     */
    public AccessOutgoing getAccessOutgoing() throws ClassCastException {
        return (AccessOutgoing)super.getActualInstance();
    }

    /**
     * Get the actual instance of `AccessQuote`. If the actual instance is not `AccessQuote`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AccessQuote`
     * @throws ClassCastException if the instance is not `AccessQuote`
     */
    public AccessQuote getAccessQuote() throws ClassCastException {
        return (AccessQuote)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof AccessIncoming) {
        if (getActualInstance() != null) {
          joiner.add(((AccessIncoming)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof AccessOutgoing) {
        if (getActualInstance() != null) {
          joiner.add(((AccessOutgoing)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof AccessQuote) {
        if (getActualInstance() != null) {
          joiner.add(((AccessQuote)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

