/*
 * Open Payments
 * The Open Payments API is a simple REST API with 4 resource types: **wallet address**, **quote**, **incoming payment** and **outgoing payment**.  The *service endpoint* for the API is always the URL of the wallet address resource and all other resources are sub-resources of the wallet address.  An incoming payment defines meta data that is automatically attached to payments made into the wallet address under that incoming payment. This facilitates automation of processes like reconciliation of payment into the wallet address with external systems.  An outgoing payment is an instruction to make a payment out of the wallet address.  A quote is a commitment from the Account Servicing Entity to deliver a particular amount to a receiver when sending a particular amount from the wallet address. It is only valid for a limited time.  All resource and collection resource representations use JSON and the media-type `application/json`.    The `wallet address` resource has three collections of sub-resources: 1. `/incoming-payments` contains the **incoming payment** sub-resources   2. `/outgoing-payments` contains the **outgoing payment** sub-resources   3. `/quotes` contains the **quote** sub-resources  Access to resources and permission to execute the methods exposed by the API is determined by the grants given to the client represented by an access token used in API requests.
 *
 * The version of the OpenAPI document: 1.4
 * Contact: tech@interledger.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fliqa.interledger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.fliqa.interledger.ApiClient;
/**
 * Amount
 */
@JsonPropertyOrder({
  Amount.JSON_PROPERTY_VALUE,
  Amount.JSON_PROPERTY_ASSET_CODE,
  Amount.JSON_PROPERTY_ASSET_SCALE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class Amount {
  public static final String JSON_PROPERTY_VALUE = "value";
  @javax.annotation.Nonnull
  private String value;

  public static final String JSON_PROPERTY_ASSET_CODE = "assetCode";
  @javax.annotation.Nonnull
  private String assetCode;

  public static final String JSON_PROPERTY_ASSET_SCALE = "assetScale";
  @javax.annotation.Nonnull
  private Integer assetScale;

  public Amount() { 
  }

  public Amount value(@javax.annotation.Nonnull String value) {
    this.value = value;
    return this;
  }

  /**
   * The value is an unsigned 64-bit integer amount, represented as a string.
   * @return value
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValue(@javax.annotation.Nonnull String value) {
    this.value = value;
  }


  public Amount assetCode(@javax.annotation.Nonnull String assetCode) {
    this.assetCode = assetCode;
    return this;
  }

  /**
   * The assetCode is a code that indicates the underlying asset. This SHOULD be an ISO4217 currency code.
   * @return assetCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASSET_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAssetCode() {
    return assetCode;
  }


  @JsonProperty(JSON_PROPERTY_ASSET_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssetCode(@javax.annotation.Nonnull String assetCode) {
    this.assetCode = assetCode;
  }


  public Amount assetScale(@javax.annotation.Nonnull Integer assetScale) {
    this.assetScale = assetScale;
    return this;
  }

  /**
   * The scale of amounts denoted in the corresponding asset code.
   * minimum: 0
   * maximum: 255
   * @return assetScale
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASSET_SCALE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getAssetScale() {
    return assetScale;
  }


  @JsonProperty(JSON_PROPERTY_ASSET_SCALE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssetScale(@javax.annotation.Nonnull Integer assetScale) {
    this.assetScale = assetScale;
  }


  /**
   * Return true if this amount object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Amount amount = (Amount) o;
    return Objects.equals(this.value, amount.value) &&
        Objects.equals(this.assetCode, amount.assetCode) &&
        Objects.equals(this.assetScale, amount.assetScale);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, assetCode, assetScale);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Amount {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    assetCode: ").append(toIndentedString(assetCode)).append("\n");
    sb.append("    assetScale: ").append(toIndentedString(assetScale)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format("%svalue%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getValue()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `assetCode` to the URL query string
    if (getAssetCode() != null) {
      joiner.add(String.format("%sassetCode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAssetCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `assetScale` to the URL query string
    if (getAssetScale() != null) {
      joiner.add(String.format("%sassetScale%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAssetScale()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

