/*
 * Open Payments
 * The Open Payments API is a simple REST API with 4 resource types: **wallet address**, **quote**, **incoming payment** and **outgoing payment**.  The *service endpoint* for the API is always the URL of the wallet address resource and all other resources are sub-resources of the wallet address.  An incoming payment defines meta data that is automatically attached to payments made into the wallet address under that incoming payment. This facilitates automation of processes like reconciliation of payment into the wallet address with external systems.  An outgoing payment is an instruction to make a payment out of the wallet address.  A quote is a commitment from the Account Servicing Entity to deliver a particular amount to a receiver when sending a particular amount from the wallet address. It is only valid for a limited time.  All resource and collection resource representations use JSON and the media-type `application/json`.    The `wallet address` resource has three collections of sub-resources: 1. `/incoming-payments` contains the **incoming payment** sub-resources   2. `/outgoing-payments` contains the **outgoing payment** sub-resources   3. `/quotes` contains the **quote** sub-resources  Access to resources and permission to execute the methods exposed by the API is determined by the grants given to the client represented by an access token used in API requests.
 *
 * The version of the OpenAPI document: 1.4
 * Contact: tech@interledger.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fliqa.interledger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.fliqa.interledger.client.model.Amount1;
import io.fliqa.interledger.client.model.IlpPaymentMethod;
import io.fliqa.interledger.client.model.IncomingPaymentWithMethods;
import io.fliqa.interledger.client.model.PublicIncomingPayment;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.fliqa.interledger.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
@JsonDeserialize(using=GetIncomingPayment200Response.GetIncomingPayment200ResponseDeserializer.class)
@JsonSerialize(using = GetIncomingPayment200Response.GetIncomingPayment200ResponseSerializer.class)
public class GetIncomingPayment200Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(GetIncomingPayment200Response.class.getName());

    public static class GetIncomingPayment200ResponseSerializer extends StdSerializer<GetIncomingPayment200Response> {
        public GetIncomingPayment200ResponseSerializer(Class<GetIncomingPayment200Response> t) {
            super(t);
        }

        public GetIncomingPayment200ResponseSerializer() {
            this(null);
        }

        @Override
        public void serialize(GetIncomingPayment200Response value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class GetIncomingPayment200ResponseDeserializer extends StdDeserializer<GetIncomingPayment200Response> {
        public GetIncomingPayment200ResponseDeserializer() {
            this(GetIncomingPayment200Response.class);
        }

        public GetIncomingPayment200ResponseDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public GetIncomingPayment200Response deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();

            Object deserialized = null;
            // deserialize IncomingPaymentWithMethods
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(IncomingPaymentWithMethods.class);
                GetIncomingPayment200Response ret = new GetIncomingPayment200Response();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'GetIncomingPayment200Response'", e);
            }

            // deserialize PublicIncomingPayment
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(PublicIncomingPayment.class);
                GetIncomingPayment200Response ret = new GetIncomingPayment200Response();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'GetIncomingPayment200Response'", e);
            }

            throw new IOException(String.format("Failed deserialization for GetIncomingPayment200Response: no match found"));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public GetIncomingPayment200Response getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "GetIncomingPayment200Response cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public GetIncomingPayment200Response() {
        super("anyOf", Boolean.FALSE);
    }

    public GetIncomingPayment200Response(IncomingPaymentWithMethods o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public GetIncomingPayment200Response(PublicIncomingPayment o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("IncomingPaymentWithMethods", IncomingPaymentWithMethods.class);
        schemas.put("PublicIncomingPayment", PublicIncomingPayment.class);
        JSON.registerDescendants(GetIncomingPayment200Response.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return GetIncomingPayment200Response.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * IncomingPaymentWithMethods, PublicIncomingPayment
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(IncomingPaymentWithMethods.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PublicIncomingPayment.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be IncomingPaymentWithMethods, PublicIncomingPayment");
    }

    /**
     * Get the actual instance, which can be the following:
     * IncomingPaymentWithMethods, PublicIncomingPayment
     *
     * @return The actual instance (IncomingPaymentWithMethods, PublicIncomingPayment)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `IncomingPaymentWithMethods`. If the actual instance is not `IncomingPaymentWithMethods`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `IncomingPaymentWithMethods`
     * @throws ClassCastException if the instance is not `IncomingPaymentWithMethods`
     */
    public IncomingPaymentWithMethods getIncomingPaymentWithMethods() throws ClassCastException {
        return (IncomingPaymentWithMethods)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PublicIncomingPayment`. If the actual instance is not `PublicIncomingPayment`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PublicIncomingPayment`
     * @throws ClassCastException if the instance is not `PublicIncomingPayment`
     */
    public PublicIncomingPayment getPublicIncomingPayment() throws ClassCastException {
        return (PublicIncomingPayment)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    return null;
  }

}

