/*
 * Open Payments
 * The Open Payments API is a simple REST API with 4 resource types: **wallet address**, **quote**, **incoming payment** and **outgoing payment**.  The *service endpoint* for the API is always the URL of the wallet address resource and all other resources are sub-resources of the wallet address.  An incoming payment defines meta data that is automatically attached to payments made into the wallet address under that incoming payment. This facilitates automation of processes like reconciliation of payment into the wallet address with external systems.  An outgoing payment is an instruction to make a payment out of the wallet address.  A quote is a commitment from the Account Servicing Entity to deliver a particular amount to a receiver when sending a particular amount from the wallet address. It is only valid for a limited time.  All resource and collection resource representations use JSON and the media-type `application/json`.    The `wallet address` resource has three collections of sub-resources: 1. `/incoming-payments` contains the **incoming payment** sub-resources   2. `/outgoing-payments` contains the **outgoing payment** sub-resources   3. `/quotes` contains the **quote** sub-resources  Access to resources and permission to execute the methods exposed by the API is determined by the grants given to the client represented by an access token used in API requests.
 *
 * The version of the OpenAPI document: 1.4
 * Contact: tech@interledger.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fliqa.interledger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.fliqa.interledger.ApiClient;
/**
 * IlpPaymentMethod
 */
@JsonPropertyOrder({
  IlpPaymentMethod.JSON_PROPERTY_TYPE,
  IlpPaymentMethod.JSON_PROPERTY_ILP_ADDRESS,
  IlpPaymentMethod.JSON_PROPERTY_SHARED_SECRET
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class IlpPaymentMethod {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    ILP(String.valueOf("ilp"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_ILP_ADDRESS = "ilpAddress";
  @javax.annotation.Nonnull
  private String ilpAddress;

  public static final String JSON_PROPERTY_SHARED_SECRET = "sharedSecret";
  @javax.annotation.Nonnull
  private String sharedSecret;

  public IlpPaymentMethod() { 
  }

  public IlpPaymentMethod type(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public IlpPaymentMethod ilpAddress(@javax.annotation.Nonnull String ilpAddress) {
    this.ilpAddress = ilpAddress;
    return this;
  }

  /**
   * The ILP address to use when establishing a STREAM connection.
   * @return ilpAddress
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ILP_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getIlpAddress() {
    return ilpAddress;
  }


  @JsonProperty(JSON_PROPERTY_ILP_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIlpAddress(@javax.annotation.Nonnull String ilpAddress) {
    this.ilpAddress = ilpAddress;
  }


  public IlpPaymentMethod sharedSecret(@javax.annotation.Nonnull String sharedSecret) {
    this.sharedSecret = sharedSecret;
    return this;
  }

  /**
   * The base64 url-encoded shared secret to use when establishing a STREAM connection.
   * @return sharedSecret
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHARED_SECRET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSharedSecret() {
    return sharedSecret;
  }


  @JsonProperty(JSON_PROPERTY_SHARED_SECRET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSharedSecret(@javax.annotation.Nonnull String sharedSecret) {
    this.sharedSecret = sharedSecret;
  }


  /**
   * Return true if this ilp-payment-method object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IlpPaymentMethod ilpPaymentMethod = (IlpPaymentMethod) o;
    return Objects.equals(this.type, ilpPaymentMethod.type) &&
        Objects.equals(this.ilpAddress, ilpPaymentMethod.ilpAddress) &&
        Objects.equals(this.sharedSecret, ilpPaymentMethod.sharedSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, ilpAddress, sharedSecret);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IlpPaymentMethod {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    ilpAddress: ").append(toIndentedString(ilpAddress)).append("\n");
    sb.append("    sharedSecret: ").append(toIndentedString(sharedSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `ilpAddress` to the URL query string
    if (getIlpAddress() != null) {
      joiner.add(String.format("%silpAddress%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getIlpAddress()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `sharedSecret` to the URL query string
    if (getSharedSecret() != null) {
      joiner.add(String.format("%ssharedSecret%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSharedSecret()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

