/*
 * Open Payments Authorization Server
 * The Open Payments API is secured via [GNAP](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol). This specification describes the Open Payments Authorization Server API, which is an opinionated GNAP Server API.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: tech@interledger.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fliqa.interledger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.fliqa.interledger.ApiClient;
/**
 * InteractResponse
 */
@JsonPropertyOrder({
  InteractResponse.JSON_PROPERTY_REDIRECT,
  InteractResponse.JSON_PROPERTY_FINISH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class InteractResponse {
  public static final String JSON_PROPERTY_REDIRECT = "redirect";
  @javax.annotation.Nonnull
  private URI redirect;

  public static final String JSON_PROPERTY_FINISH = "finish";
  @javax.annotation.Nonnull
  private String finish;

  public InteractResponse() { 
  }

  public InteractResponse redirect(@javax.annotation.Nonnull URI redirect) {
    this.redirect = redirect;
    return this;
  }

  /**
   * The URI to direct the end user to.
   * @return redirect
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REDIRECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getRedirect() {
    return redirect;
  }


  @JsonProperty(JSON_PROPERTY_REDIRECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRedirect(@javax.annotation.Nonnull URI redirect) {
    this.redirect = redirect;
  }


  public InteractResponse finish(@javax.annotation.Nonnull String finish) {
    this.finish = finish;
    return this;
  }

  /**
   * Unique key to secure the callback.
   * @return finish
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FINISH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFinish() {
    return finish;
  }


  @JsonProperty(JSON_PROPERTY_FINISH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFinish(@javax.annotation.Nonnull String finish) {
    this.finish = finish;
  }


  /**
   * Return true if this interact-response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InteractResponse interactResponse = (InteractResponse) o;
    return Objects.equals(this.redirect, interactResponse.redirect) &&
        Objects.equals(this.finish, interactResponse.finish);
  }

  @Override
  public int hashCode() {
    return Objects.hash(redirect, finish);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InteractResponse {\n");
    sb.append("    redirect: ").append(toIndentedString(redirect)).append("\n");
    sb.append("    finish: ").append(toIndentedString(finish)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `redirect` to the URL query string
    if (getRedirect() != null) {
      joiner.add(String.format("%sredirect%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRedirect()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `finish` to the URL query string
    if (getFinish() != null) {
      joiner.add(String.format("%sfinish%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFinish()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

