/*
 * Open Payments Authorization Server
 * The Open Payments API is secured via [GNAP](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol). This specification describes the Open Payments Authorization Server API, which is an opinionated GNAP Server API.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: tech@interledger.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fliqa.interledger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.fliqa.interledger.ApiClient;
/**
 * Open Payments specific property that defines the limits under which outgoing payments can be created.
 */
@JsonPropertyOrder({
  LimitsOutgoing.JSON_PROPERTY_RECEIVER,
  LimitsOutgoing.JSON_PROPERTY_DEBIT_AMOUNT,
  LimitsOutgoing.JSON_PROPERTY_RECEIVE_AMOUNT,
  LimitsOutgoing.JSON_PROPERTY_INTERVAL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class LimitsOutgoing {
  public static final String JSON_PROPERTY_RECEIVER = "receiver";
  @javax.annotation.Nullable
  private URI receiver;

  public static final String JSON_PROPERTY_DEBIT_AMOUNT = "debitAmount";
  @javax.annotation.Nullable
  private Object debitAmount;

  public static final String JSON_PROPERTY_RECEIVE_AMOUNT = "receiveAmount";
  @javax.annotation.Nullable
  private Object receiveAmount;

  public static final String JSON_PROPERTY_INTERVAL = "interval";
  @javax.annotation.Nullable
  private String interval;

  public LimitsOutgoing() { 
  }

  public LimitsOutgoing receiver(@javax.annotation.Nullable URI receiver) {
    this.receiver = receiver;
    return this;
  }

  /**
   * The URL of the incoming payment that is being paid.
   * @return receiver
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECEIVER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getReceiver() {
    return receiver;
  }


  @JsonProperty(JSON_PROPERTY_RECEIVER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReceiver(@javax.annotation.Nullable URI receiver) {
    this.receiver = receiver;
  }


  public LimitsOutgoing debitAmount(@javax.annotation.Nullable Object debitAmount) {
    this.debitAmount = debitAmount;
    return this;
  }

  /**
   * Get debitAmount
   * @return debitAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEBIT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getDebitAmount() {
    return debitAmount;
  }


  @JsonProperty(JSON_PROPERTY_DEBIT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDebitAmount(@javax.annotation.Nullable Object debitAmount) {
    this.debitAmount = debitAmount;
  }


  public LimitsOutgoing receiveAmount(@javax.annotation.Nullable Object receiveAmount) {
    this.receiveAmount = receiveAmount;
    return this;
  }

  /**
   * Get receiveAmount
   * @return receiveAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECEIVE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getReceiveAmount() {
    return receiveAmount;
  }


  @JsonProperty(JSON_PROPERTY_RECEIVE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReceiveAmount(@javax.annotation.Nullable Object receiveAmount) {
    this.receiveAmount = receiveAmount;
  }


  public LimitsOutgoing interval(@javax.annotation.Nullable String interval) {
    this.interval = interval;
    return this;
  }

  /**
   * [ISO8601 repeating interval](https://en.wikipedia.org/wiki/ISO_8601#Repeating_intervals)
   * @return interval
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getInterval() {
    return interval;
  }


  @JsonProperty(JSON_PROPERTY_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterval(@javax.annotation.Nullable String interval) {
    this.interval = interval;
  }


  /**
   * Return true if this limits-outgoing object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LimitsOutgoing limitsOutgoing = (LimitsOutgoing) o;
    return Objects.equals(this.receiver, limitsOutgoing.receiver) &&
        Objects.equals(this.debitAmount, limitsOutgoing.debitAmount) &&
        Objects.equals(this.receiveAmount, limitsOutgoing.receiveAmount) &&
        Objects.equals(this.interval, limitsOutgoing.interval);
  }

  @Override
  public int hashCode() {
    return Objects.hash(receiver, debitAmount, receiveAmount, interval);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LimitsOutgoing {\n");
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("    debitAmount: ").append(toIndentedString(debitAmount)).append("\n");
    sb.append("    receiveAmount: ").append(toIndentedString(receiveAmount)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    return joiner.toString();
  }
}

