/*
 * Open Payments Authorization Server
 * The Open Payments API is secured via [GNAP](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol). This specification describes the Open Payments Authorization Server API, which is an opinionated GNAP Server API.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: tech@interledger.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fliqa.interledger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.fliqa.interledger.client.model.InteractResponse;
import io.fliqa.interledger.client.model.ModelContinue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.fliqa.interledger.ApiClient;
/**
 * PostRequest200ResponseOneOf
 */
@JsonPropertyOrder({
  PostRequest200ResponseOneOf.JSON_PROPERTY_INTERACT,
  PostRequest200ResponseOneOf.JSON_PROPERTY_CONTINUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class PostRequest200ResponseOneOf {
  public static final String JSON_PROPERTY_INTERACT = "interact";
  @javax.annotation.Nonnull
  private InteractResponse interact;

  public static final String JSON_PROPERTY_CONTINUE = "continue";
  @javax.annotation.Nonnull
  private ModelContinue _continue;

  public PostRequest200ResponseOneOf() { 
  }

  public PostRequest200ResponseOneOf interact(@javax.annotation.Nonnull InteractResponse interact) {
    this.interact = interact;
    return this;
  }

  /**
   * Get interact
   * @return interact
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INTERACT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public InteractResponse getInteract() {
    return interact;
  }


  @JsonProperty(JSON_PROPERTY_INTERACT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInteract(@javax.annotation.Nonnull InteractResponse interact) {
    this.interact = interact;
  }


  public PostRequest200ResponseOneOf _continue(@javax.annotation.Nonnull ModelContinue _continue) {
    this._continue = _continue;
    return this;
  }

  /**
   * Get _continue
   * @return _continue
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONTINUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ModelContinue getContinue() {
    return _continue;
  }


  @JsonProperty(JSON_PROPERTY_CONTINUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContinue(@javax.annotation.Nonnull ModelContinue _continue) {
    this._continue = _continue;
  }


  /**
   * Return true if this post_request_200_response_oneOf object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostRequest200ResponseOneOf postRequest200ResponseOneOf = (PostRequest200ResponseOneOf) o;
    return Objects.equals(this.interact, postRequest200ResponseOneOf.interact) &&
        Objects.equals(this._continue, postRequest200ResponseOneOf._continue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interact, _continue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostRequest200ResponseOneOf {\n");
    sb.append("    interact: ").append(toIndentedString(interact)).append("\n");
    sb.append("    _continue: ").append(toIndentedString(_continue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `interact` to the URL query string
    if (getInteract() != null) {
      joiner.add(getInteract().toUrlQueryString(prefix + "interact" + suffix));
    }

    // add `continue` to the URL query string
    if (getContinue() != null) {
      joiner.add(getContinue().toUrlQueryString(prefix + "continue" + suffix));
    }

    return joiner.toString();
  }
}

