/*
 * Open Payments Authorization Server
 * The Open Payments API is secured via [GNAP](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol). This specification describes the Open Payments Authorization Server API, which is an opinionated GNAP Server API.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: tech@interledger.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fliqa.interledger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.fliqa.interledger.ApiClient;
/**
 * PostContinueRequest
 */
@JsonPropertyOrder({
  PostContinueRequest.JSON_PROPERTY_INTERACT_REF
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class PostContinueRequest {
  public static final String JSON_PROPERTY_INTERACT_REF = "interact_ref";
  @javax.annotation.Nullable
  private String interactRef;

  public PostContinueRequest() { 
  }

  public PostContinueRequest interactRef(@javax.annotation.Nullable String interactRef) {
    this.interactRef = interactRef;
    return this;
  }

  /**
   * The interaction reference generated for this interaction by the AS.
   * @return interactRef
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERACT_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getInteractRef() {
    return interactRef;
  }


  @JsonProperty(JSON_PROPERTY_INTERACT_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInteractRef(@javax.annotation.Nullable String interactRef) {
    this.interactRef = interactRef;
  }


  /**
   * Return true if this post_continue_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostContinueRequest postContinueRequest = (PostContinueRequest) o;
    return Objects.equals(this.interactRef, postContinueRequest.interactRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interactRef);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostContinueRequest {\n");
    sb.append("    interactRef: ").append(toIndentedString(interactRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `interact_ref` to the URL query string
    if (getInteractRef() != null) {
      joiner.add(String.format("%sinteract_ref%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getInteractRef()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

