/*
 * Open Payments Authorization Server
 * The Open Payments API is secured via [GNAP](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol). This specification describes the Open Payments Authorization Server API, which is an opinionated GNAP Server API.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: tech@interledger.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fliqa.interledger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.fliqa.interledger.client.model.AccessToken;
import io.fliqa.interledger.client.model.InteractResponse;
import io.fliqa.interledger.client.model.ModelContinue;
import io.fliqa.interledger.client.model.PostRequest200ResponseOneOf;
import io.fliqa.interledger.client.model.PostRequest200ResponseOneOf1;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.fliqa.interledger.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
@JsonDeserialize(using = PostRequest200Response.PostRequest200ResponseDeserializer.class)
@JsonSerialize(using = PostRequest200Response.PostRequest200ResponseSerializer.class)
public class PostRequest200Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(PostRequest200Response.class.getName());

    public static class PostRequest200ResponseSerializer extends StdSerializer<PostRequest200Response> {
        public PostRequest200ResponseSerializer(Class<PostRequest200Response> t) {
            super(t);
        }

        public PostRequest200ResponseSerializer() {
            this(null);
        }

        @Override
        public void serialize(PostRequest200Response value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class PostRequest200ResponseDeserializer extends StdDeserializer<PostRequest200Response> {
        public PostRequest200ResponseDeserializer() {
            this(PostRequest200Response.class);
        }

        public PostRequest200ResponseDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public PostRequest200Response deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize PostRequest200ResponseOneOf
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PostRequest200ResponseOneOf.class.equals(Integer.class) || PostRequest200ResponseOneOf.class.equals(Long.class) || PostRequest200ResponseOneOf.class.equals(Float.class) || PostRequest200ResponseOneOf.class.equals(Double.class) || PostRequest200ResponseOneOf.class.equals(Boolean.class) || PostRequest200ResponseOneOf.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PostRequest200ResponseOneOf.class.equals(Integer.class) || PostRequest200ResponseOneOf.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PostRequest200ResponseOneOf.class.equals(Float.class) || PostRequest200ResponseOneOf.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PostRequest200ResponseOneOf.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PostRequest200ResponseOneOf.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PostRequest200ResponseOneOf.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PostRequest200ResponseOneOf'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PostRequest200ResponseOneOf'", e);
            }

            // deserialize PostRequest200ResponseOneOf1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PostRequest200ResponseOneOf1.class.equals(Integer.class) || PostRequest200ResponseOneOf1.class.equals(Long.class) || PostRequest200ResponseOneOf1.class.equals(Float.class) || PostRequest200ResponseOneOf1.class.equals(Double.class) || PostRequest200ResponseOneOf1.class.equals(Boolean.class) || PostRequest200ResponseOneOf1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PostRequest200ResponseOneOf1.class.equals(Integer.class) || PostRequest200ResponseOneOf1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PostRequest200ResponseOneOf1.class.equals(Float.class) || PostRequest200ResponseOneOf1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PostRequest200ResponseOneOf1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PostRequest200ResponseOneOf1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PostRequest200ResponseOneOf1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PostRequest200ResponseOneOf1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PostRequest200ResponseOneOf1'", e);
            }

            if (match == 1) {
                PostRequest200Response ret = new PostRequest200Response();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for PostRequest200Response: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public PostRequest200Response getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "PostRequest200Response cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public PostRequest200Response() {
        super("oneOf", Boolean.FALSE);
    }

    public PostRequest200Response(PostRequest200ResponseOneOf o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PostRequest200Response(PostRequest200ResponseOneOf1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("PostRequest200ResponseOneOf", PostRequest200ResponseOneOf.class);
        schemas.put("PostRequest200ResponseOneOf1", PostRequest200ResponseOneOf1.class);
        JSON.registerDescendants(PostRequest200Response.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return PostRequest200Response.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * PostRequest200ResponseOneOf, PostRequest200ResponseOneOf1
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(PostRequest200ResponseOneOf.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PostRequest200ResponseOneOf1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be PostRequest200ResponseOneOf, PostRequest200ResponseOneOf1");
    }

    /**
     * Get the actual instance, which can be the following:
     * PostRequest200ResponseOneOf, PostRequest200ResponseOneOf1
     *
     * @return The actual instance (PostRequest200ResponseOneOf, PostRequest200ResponseOneOf1)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `PostRequest200ResponseOneOf`. If the actual instance is not `PostRequest200ResponseOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PostRequest200ResponseOneOf`
     * @throws ClassCastException if the instance is not `PostRequest200ResponseOneOf`
     */
    public PostRequest200ResponseOneOf getPostRequest200ResponseOneOf() throws ClassCastException {
        return (PostRequest200ResponseOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PostRequest200ResponseOneOf1`. If the actual instance is not `PostRequest200ResponseOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PostRequest200ResponseOneOf1`
     * @throws ClassCastException if the instance is not `PostRequest200ResponseOneOf1`
     */
    public PostRequest200ResponseOneOf1 getPostRequest200ResponseOneOf1() throws ClassCastException {
        return (PostRequest200ResponseOneOf1)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof PostRequest200ResponseOneOf) {
        if (getActualInstance() != null) {
          joiner.add(((PostRequest200ResponseOneOf)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof PostRequest200ResponseOneOf1) {
        if (getActualInstance() != null) {
          joiner.add(((PostRequest200ResponseOneOf1)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

