/*
 * Open Payments Authorization Server
 * The Open Payments API is secured via [GNAP](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol). This specification describes the Open Payments Authorization Server API, which is an opinionated GNAP Server API.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: tech@interledger.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fliqa.interledger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.fliqa.interledger.client.model.InteractRequest;
import io.fliqa.interledger.client.model.PostRequestRequestAccessToken;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.fliqa.interledger.ApiClient;
/**
 * 
 */
@JsonPropertyOrder({
  PostRequestRequest.JSON_PROPERTY_ACCESS_TOKEN,
  PostRequestRequest.JSON_PROPERTY_CLIENT,
  PostRequestRequest.JSON_PROPERTY_INTERACT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class PostRequestRequest {
  public static final String JSON_PROPERTY_ACCESS_TOKEN = "access_token";
  @javax.annotation.Nonnull
  private PostRequestRequestAccessToken accessToken;

  public static final String JSON_PROPERTY_CLIENT = "client";
  @javax.annotation.Nonnull
  private String client;

  public static final String JSON_PROPERTY_INTERACT = "interact";
  @javax.annotation.Nullable
  private InteractRequest interact;

  public PostRequestRequest() { 
  }

  public PostRequestRequest accessToken(@javax.annotation.Nonnull PostRequestRequestAccessToken accessToken) {
    this.accessToken = accessToken;
    return this;
  }

  /**
   * Get accessToken
   * @return accessToken
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCESS_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PostRequestRequestAccessToken getAccessToken() {
    return accessToken;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccessToken(@javax.annotation.Nonnull PostRequestRequestAccessToken accessToken) {
    this.accessToken = accessToken;
  }


  public PostRequestRequest client(@javax.annotation.Nonnull String client) {
    this.client = client;
    return this;
  }

  /**
   * Wallet address of the client instance that is making this request.  When sending a non-continuation request to the AS, the client instance MUST identify itself by including the client field of the request and by signing the request.  A JSON Web Key Set document, including the public key that the client instance will use to protect this request and any continuation requests at the AS and any user-facing information about the client instance used in interactions, MUST be available at the wallet address + &#x60;/jwks.json&#x60; url.  If sending a grant initiation request that requires RO interaction, the wallet address MUST serve necessary client display information.
   * @return client
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLIENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getClient() {
    return client;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClient(@javax.annotation.Nonnull String client) {
    this.client = client;
  }


  public PostRequestRequest interact(@javax.annotation.Nullable InteractRequest interact) {
    this.interact = interact;
    return this;
  }

  /**
   * Get interact
   * @return interact
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public InteractRequest getInteract() {
    return interact;
  }


  @JsonProperty(JSON_PROPERTY_INTERACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInteract(@javax.annotation.Nullable InteractRequest interact) {
    this.interact = interact;
  }


  /**
   * Return true if this post_request_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostRequestRequest postRequestRequest = (PostRequestRequest) o;
    return Objects.equals(this.accessToken, postRequestRequest.accessToken) &&
        Objects.equals(this.client, postRequestRequest.client) &&
        Objects.equals(this.interact, postRequestRequest.interact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken, client, interact);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostRequestRequest {\n");
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    client: ").append(toIndentedString(client)).append("\n");
    sb.append("    interact: ").append(toIndentedString(interact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `access_token` to the URL query string
    if (getAccessToken() != null) {
      joiner.add(getAccessToken().toUrlQueryString(prefix + "access_token" + suffix));
    }

    // add `client` to the URL query string
    if (getClient() != null) {
      joiner.add(String.format("%sclient%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getClient()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `interact` to the URL query string
    if (getInteract() != null) {
      joiner.add(getInteract().toUrlQueryString(prefix + "interact" + suffix));
    }

    return joiner.toString();
  }
}

