/*
 * Open Payments
 * The Open Payments API is a simple REST API with 4 resource types: **wallet address**, **quote**, **incoming payment** and **outgoing payment**.  The *service endpoint* for the API is always the URL of the wallet address resource and all other resources are sub-resources of the wallet address.  An incoming payment defines meta data that is automatically attached to payments made into the wallet address under that incoming payment. This facilitates automation of processes like reconciliation of payment into the wallet address with external systems.  An outgoing payment is an instruction to make a payment out of the wallet address.  A quote is a commitment from the Account Servicing Entity to deliver a particular amount to a receiver when sending a particular amount from the wallet address. It is only valid for a limited time.  All resource and collection resource representations use JSON and the media-type `application/json`.    The `wallet address` resource has three collections of sub-resources: 1. `/incoming-payments` contains the **incoming payment** sub-resources   2. `/outgoing-payments` contains the **outgoing payment** sub-resources   3. `/quotes` contains the **quote** sub-resources  Access to resources and permission to execute the methods exposed by the API is determined by the grants given to the client represented by an access token used in API requests.
 *
 * The version of the OpenAPI document: 1.4
 * Contact: tech@interledger.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fliqa.interledger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.fliqa.interledger.client.model.Amount1;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.fliqa.interledger.ApiClient;
/**
 * An **incoming payment** resource with public details.
 */
@JsonPropertyOrder({
  PublicIncomingPayment.JSON_PROPERTY_RECEIVED_AMOUNT,
  PublicIncomingPayment.JSON_PROPERTY_AUTH_SERVER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class PublicIncomingPayment {
  public static final String JSON_PROPERTY_RECEIVED_AMOUNT = "receivedAmount";
  @javax.annotation.Nullable
  private Amount1 receivedAmount;

  public static final String JSON_PROPERTY_AUTH_SERVER = "authServer";
  @javax.annotation.Nonnull
  private URI authServer;

  public PublicIncomingPayment() { 
  }

  public PublicIncomingPayment receivedAmount(@javax.annotation.Nullable Amount1 receivedAmount) {
    this.receivedAmount = receivedAmount;
    return this;
  }

  /**
   * Get receivedAmount
   * @return receivedAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECEIVED_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Amount1 getReceivedAmount() {
    return receivedAmount;
  }


  @JsonProperty(JSON_PROPERTY_RECEIVED_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReceivedAmount(@javax.annotation.Nullable Amount1 receivedAmount) {
    this.receivedAmount = receivedAmount;
  }


  public PublicIncomingPayment authServer(@javax.annotation.Nonnull URI authServer) {
    this.authServer = authServer;
    return this;
  }

  /**
   * The URL of the authorization server endpoint for getting grants and access tokens for this wallet address.
   * @return authServer
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AUTH_SERVER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getAuthServer() {
    return authServer;
  }


  @JsonProperty(JSON_PROPERTY_AUTH_SERVER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthServer(@javax.annotation.Nonnull URI authServer) {
    this.authServer = authServer;
  }


  /**
   * Return true if this public-incoming-payment object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicIncomingPayment publicIncomingPayment = (PublicIncomingPayment) o;
    return Objects.equals(this.receivedAmount, publicIncomingPayment.receivedAmount) &&
        Objects.equals(this.authServer, publicIncomingPayment.authServer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(receivedAmount, authServer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicIncomingPayment {\n");
    sb.append("    receivedAmount: ").append(toIndentedString(receivedAmount)).append("\n");
    sb.append("    authServer: ").append(toIndentedString(authServer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `receivedAmount` to the URL query string
    if (getReceivedAmount() != null) {
      joiner.add(getReceivedAmount().toUrlQueryString(prefix + "receivedAmount" + suffix));
    }

    // add `authServer` to the URL query string
    if (getAuthServer() != null) {
      joiner.add(String.format("%sauthServer%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAuthServer()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

