name: Publish Interledger API client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Remove SNAPSHOT from version
        id: get_version
        run: |
          # Extract version from build.gradle.kts
          PACKAGE_VERSION=$(grep -o 'version = "[^"]*"' build.gradle.kts | cut -d'"' -f2)
          # Remove -SNAPSHOT suffix
          RELEASE_VERSION="${PACKAGE_VERSION/-SNAPSHOT/}"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "Version for release: $RELEASE_VERSION"

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        run: ./gradlew publish -Prelease.version=2.0.0
